/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NostalgiaLetterRouteImport } from './routes/nostalgia-letter'
import { Route as IndexRouteImport } from './routes/index'

const NostalgiaLetterRoute = NostalgiaLetterRouteImport.update({
  id: '/nostalgia-letter',
  path: '/nostalgia-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nostalgia-letter': typeof NostalgiaLetterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nostalgia-letter': typeof NostalgiaLetterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nostalgia-letter': typeof NostalgiaLetterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nostalgia-letter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nostalgia-letter'
  id: '__root__' | '/' | '/nostalgia-letter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NostalgiaLetterRoute: typeof NostalgiaLetterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nostalgia-letter': {
      id: '/nostalgia-letter'
      path: '/nostalgia-letter'
      fullPath: '/nostalgia-letter'
      preLoaderRoute: typeof NostalgiaLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NostalgiaLetterRoute: NostalgiaLetterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
